# Generated by Django 2.2.16 on 2022-12-03 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221203_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='HEX color required', regex='^#(?:[0-9a-fA-F]{1,2}){3}$')]),
        ),
    ]
